version: '3.8'

services:
  # Serviço para o app Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html/src
    volumes:
      - ./src:/var/www/html/src
    networks:
      - laravel

  # Serviço para o Nginx
  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    depends_on:
      - app
    volumes:
      - ./src:/var/www/html/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - laravel

  # Serviço para o PostgreSQL
  db:
    image: postgres:13
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5450:5432"
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
    driver: local
